name: deranged
description: Generic range and progression classes, inspired by Rust and Kotlin
version: 0.0.0
repository: https://github.com/JonasWanke/deranged

environment:
  sdk: ^3.1.0

dependencies:
  collection: ^1.15.0
  json_annotation: ^4.9.0
  meta: ^1.3.0

dev_dependencies:
  glados: ^1.1.7
  supernova_lints:
    git:
      url: https://github.com/JonasWanke/supernova.git
      path: supernova_lints
      ref: 3b8fc18a1f2a65153763a8e7528f68997c00808f
  test: ^1.16.8
